import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { getSettings, getStoredToken, setStoredToken } from '@/services/api'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'

function maskToken(t: string): string {
  if (!t) return '<not set>'
  if (t.length <= 12) return '<short>'
  return t.slice(0, 5) + 'xxxx...' + t.slice(-4)
}

export default function Settings() {
  const settings = useQuery({ queryKey: ['settings'], queryFn: getSettings })
  const [tokenInput, setTokenInput] = useState('')
  const [savedToken, setSavedToken] = useState(getStoredToken())

  const save = () => {
    setStoredToken(tokenInput)
    setSavedToken(tokenInput)
    setTokenInput('')
  }

  const clear = () => {
    setStoredToken('')
    setSavedToken('')
  }

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Settings</h1>

      <Card>
        <CardHeader>
          <CardTitle>Admin token</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="text-sm text-muted-foreground">
            The token is generated by the server on first boot — look for{' '}
            <code className="text-xs bg-muted px-1 py-0.5 rounded">==&gt; env-manager admin token</code>{' '}
            in the server log. Stored in your browser's localStorage; sent as{' '}
            <code className="text-xs">Authorization: Bearer</code> on mutating requests.
          </div>
          <div>
            <span className="text-sm text-muted-foreground">Currently stored: </span>
            <code className="text-xs font-mono">{maskToken(savedToken)}</code>
          </div>
          <div className="flex gap-2">
            <Input
              type="password"
              placeholder="envm_..."
              value={tokenInput}
              onChange={(e) => setTokenInput(e.target.value)}
              className="max-w-md"
            />
            <Button onClick={save} disabled={!tokenInput}>
              Save
            </Button>
            <Button variant="outline" onClick={clear} disabled={!savedToken}>
              Clear
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Server configuration</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm">
          <div className="flex justify-between">
            <span className="text-muted-foreground">Version</span>
            <code className="font-mono">{settings.data?.version || '—'}</code>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-muted-foreground">LETSENCRYPT_EMAIL</span>
            <Badge variant={settings.data?.letsencrypt_email_set ? 'default' : 'secondary'}>
              {settings.data?.letsencrypt_email_set ? 'configured' : 'unset'}
            </Badge>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-muted-foreground">Credential store</span>
            <Badge variant={settings.data?.credential_store_set ? 'default' : 'destructive'}>
              {settings.data?.credential_store_set ? 'ready' : 'unavailable'}
            </Badge>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
