import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { getSettings, getStoredToken, setStoredToken } from '@/services/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

// Stitch design language applied to settings: card panels, dense rows,
// status pills with the project's success/warning/destructive tokens.

function maskToken(t: string): string {
  if (!t) return '<not set>'
  if (t.length <= 12) return '<short>'
  return t.slice(0, 5) + 'xxxx...' + t.slice(-4)
}

const STATUS_TOKENS = {
  ok: { dot: 'bg-primary', text: 'text-primary', bg: 'bg-primary/10', border: 'border-primary/30' },
  warn: { dot: 'bg-warning', text: 'text-warning', bg: 'bg-warning/10', border: 'border-warning/30' },
  bad: { dot: 'bg-destructive', text: 'text-destructive', bg: 'bg-destructive/10', border: 'border-destructive/30' },
  muted: { dot: 'bg-muted-foreground', text: 'text-muted-foreground', bg: 'bg-secondary', border: 'border-border' },
} as const

function StatusPill({
  variant,
  children,
}: {
  variant: keyof typeof STATUS_TOKENS
  children: React.ReactNode
}) {
  const tok = STATUS_TOKENS[variant]
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider font-medium',
        tok.border,
        tok.bg,
        tok.text
      )}
    >
      <span className={cn('h-1.5 w-1.5 rounded-full', tok.dot)} />
      {children}
    </span>
  )
}

export default function Settings() {
  const settings = useQuery({ queryKey: ['settings'], queryFn: getSettings })
  const [tokenInput, setTokenInput] = useState('')
  const [savedToken, setSavedToken] = useState(getStoredToken())

  const save = () => {
    setStoredToken(tokenInput)
    setSavedToken(tokenInput)
    setTokenInput('')
  }

  const clear = () => {
    setStoredToken('')
    setSavedToken('')
  }

  return (
    <div className="px-6 py-6 space-y-6 max-w-[1400px] mx-auto">
      <header>
        <h1 className="text-[28px] font-semibold tracking-tight leading-none">Settings</h1>
        <p className="mt-1.5 text-sm text-muted-foreground">
          Admin token, server configuration, and credential store status.
        </p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Admin token */}
        <div className="rounded-lg border border-border bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-border bg-background/40">
            <h2 className="text-[12px] font-semibold uppercase tracking-wider">Admin token</h2>
          </div>
          <div className="p-4 space-y-3">
            <p className="text-[12px] text-muted-foreground leading-relaxed">
              Generated by the server on first boot — look for{' '}
              <code className="font-mono text-foreground">==&gt; env-manager admin token</code> in
              the server log. Stored in your browser&rsquo;s localStorage; sent as{' '}
              <code className="font-mono text-foreground">Authorization: Bearer</code> on mutating
              requests.
            </p>
            <div className="text-[12px]">
              <span className="text-muted-foreground">Currently stored: </span>
              <code className="font-mono text-foreground">{maskToken(savedToken)}</code>
            </div>
            <div className="flex gap-2 pt-1 flex-wrap">
              <Input
                type="password"
                placeholder="envm_..."
                value={tokenInput}
                onChange={(e) => setTokenInput(e.target.value)}
                className="max-w-md flex-1 min-w-[200px]"
              />
              <Button onClick={save} disabled={!tokenInput} size="sm" className="h-9">
                Save
              </Button>
              <Button variant="outline" size="sm" className="h-9" onClick={clear} disabled={!savedToken}>
                Clear
              </Button>
            </div>
          </div>
        </div>

        {/* Server configuration */}
        <div className="rounded-lg border border-border bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-border bg-background/40">
            <h2 className="text-[12px] font-semibold uppercase tracking-wider">
              Server configuration
            </h2>
          </div>
          <div className="p-4">
            <dl className="text-[12px] space-y-0">
              <Row label="version" value={<span className="font-mono">{settings.data?.version || '—'}</span>} />
              <Row
                label="letsencrypt_email"
                value={
                  <StatusPill variant={settings.data?.letsencrypt_email_set ? 'ok' : 'muted'}>
                    {settings.data?.letsencrypt_email_set ? 'configured' : 'unset'}
                  </StatusPill>
                }
              />
              <Row
                label="credential store"
                value={
                  <StatusPill variant={settings.data?.credential_store_set ? 'ok' : 'bad'}>
                    {settings.data?.credential_store_set ? 'ready' : 'unavailable'}
                  </StatusPill>
                }
                last
              />
            </dl>
          </div>
        </div>
      </div>
    </div>
  )
}

function Row({
  label,
  value,
  last,
}: {
  label: string
  value: React.ReactNode
  last?: boolean
}) {
  return (
    <div
      className={cn(
        'flex justify-between items-center py-2.5 gap-3',
        !last && 'border-b border-border'
      )}
    >
      <dt className="font-mono text-[11px] text-muted-foreground uppercase tracking-wider">
        {label}
      </dt>
      <dd>{value}</dd>
    </div>
  )
}
