import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { getSettings, getStoredToken, setStoredToken } from '@/services/api'
import { Section } from '@/components/ui/section'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'

function maskToken(t: string): string {
  if (!t) return '<not set>'
  if (t.length <= 12) return '<short>'
  return t.slice(0, 5) + 'xxxx...' + t.slice(-4)
}

export default function Settings() {
  const settings = useQuery({ queryKey: ['settings'], queryFn: getSettings })
  const [tokenInput, setTokenInput] = useState('')
  const [savedToken, setSavedToken] = useState(getStoredToken())

  const save = () => {
    setStoredToken(tokenInput)
    setSavedToken(tokenInput)
    setTokenInput('')
  }

  const clear = () => {
    setStoredToken('')
    setSavedToken('')
  }

  return (
    <div className="p-6 space-y-4 max-w-3xl">
      <header>
        <h1 className="text-xl font-semibold">Settings</h1>
      </header>

      <Section title="Admin token">
        <p className="text-xs text-muted-foreground leading-relaxed">
          The token is generated by the server on first boot — look for{' '}
          <code className="font-mono">==&gt; env-manager admin token</code> in the server log. Stored
          in your browser&rsquo;s localStorage; sent as{' '}
          <code className="font-mono">Authorization: Bearer</code> on mutating requests.
        </p>
        <div className="text-xs">
          <span className="text-muted-foreground">Currently stored: </span>
          <code className="font-mono text-foreground">{maskToken(savedToken)}</code>
        </div>
        <div className="flex gap-2 pt-1">
          <Input
            type="password"
            placeholder="envm_..."
            value={tokenInput}
            onChange={(e) => setTokenInput(e.target.value)}
            className="max-w-md"
          />
          <Button onClick={save} disabled={!tokenInput}>
            Save
          </Button>
          <Button variant="outline" onClick={clear} disabled={!savedToken}>
            Clear
          </Button>
        </div>
      </Section>

      <Section title="Server configuration">
        <dl className="text-xs space-y-2">
          <div className="flex justify-between items-center">
            <dt className="text-muted-foreground">Version</dt>
            <dd className="font-mono">{settings.data?.version || '—'}</dd>
          </div>
          <div className="flex justify-between items-center">
            <dt className="text-muted-foreground">LETSENCRYPT_EMAIL</dt>
            <dd>
              <Badge variant={settings.data?.letsencrypt_email_set ? 'success' : 'default'}>
                {settings.data?.letsencrypt_email_set ? 'configured' : 'unset'}
              </Badge>
            </dd>
          </div>
          <div className="flex justify-between items-center">
            <dt className="text-muted-foreground">Credential store</dt>
            <dd>
              <Badge variant={settings.data?.credential_store_set ? 'success' : 'failed'}>
                {settings.data?.credential_store_set ? 'ready' : 'unavailable'}
              </Badge>
            </dd>
          </div>
        </dl>
      </Section>
    </div>
  )
}
