// Command envm is the env-manager CLI. Subcommand-per-noun pattern:
//
//	envm secrets list <project>
//	envm secrets set <project> KEY=VALUE [...]
//	envm secrets get <project> KEY --reveal
//	envm secrets delete <project> KEY
//	envm secrets import <project> path/to/.env
//	envm secrets check <project>
//	envm config show
//	envm version
//
// Project/build/env management commands ship in Plan 6b.
//
// Configuration: ~/.envm/config.yaml with `endpoint:` and `token:` fields.
// The token is generated by env-manager on first boot and printed once to
// the server log.
package main

import (
	"fmt"
	"os"
)

// version is set at build time via `-ldflags "-X main.version=..."`.
var version = "dev"

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "version", "-v", "--version":
		fmt.Println("envm", version)
		return
	case "config":
		runConfig(os.Args[2:])
	case "secrets":
		runSecrets(os.Args[2:])
	case "projects":
		runProjects(os.Args[2:])
	case "help", "-h", "--help":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command %q\n\n", os.Args[1])
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `envm — env-manager CLI

Usage:
  envm secrets list <project>
  envm secrets set <project> KEY=VALUE [...]
  envm secrets get <project> KEY --reveal
  envm secrets delete <project> KEY
  envm secrets import <project> path/to/.env
  envm secrets check <project>
  envm projects list
  envm projects onboard <git-url> [--token PAT]
  envm projects show <project-id>
  envm projects delete <project-id> [--yes]
  envm config show
  envm version

Configuration: ~/.envm/config.yaml
  endpoint: https://manager.example.com
  token: envm_<from-server-startup-log>`)
}

// runConfig dispatches `envm config <subcommand>`.
func runConfig(args []string) {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "usage: envm config show")
		os.Exit(2)
	}
	switch args[0] {
	case "show":
		cfg, err := loadConfig()
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		// Don't print the token — show only its presence + length.
		fmt.Printf("endpoint: %s\n", cfg.Endpoint)
		fmt.Printf("token:    %s (length=%d)\n", maskToken(cfg.Token), len(cfg.Token))
	default:
		fmt.Fprintf(os.Stderr, "unknown config subcommand %q\n", args[0])
		os.Exit(2)
	}
}

// maskToken returns "envm_xxxx...yyyy" preserving the prefix and last 4 chars.
func maskToken(token string) string {
	if len(token) <= 12 {
		return "<short>"
	}
	return token[:5] + "xxxx..." + token[len(token)-4:]
}
